social_site_clone_project/simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'),
    name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name="logout"),
    url(r'signup/$',views.SignUp.as_view(),name='signup')
]

social_site_clone_project/simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.conf.urls import include,url
from simplesocial import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name="home"),
    url(r'accounts/',include('accounts.urls',namespace='accounts')),
    url(r'accounts/',include('django.contrib.auth.urls')),
    url(r'test/$',views.TestPage.as_view(),name='test'),
    url(r'thanks/$',views.ThankPage.as_view(),name='thanks'),
]

social_site_clone_project/simplesocial/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

social_site_clone_project/simplesocial/groups/models.py
from django.db import models

# Create your models here.

social_site_clone_project/simplesocial/posts/models.py
from django.db import models

# Create your models here.

social_site_clone_project/simplesocial/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta():
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display name'
        self.fields['email'].label = 'Email Address'

social_site_clone_project/simplesocial/accounts/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from . import forms
# Create your views here...
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name ='accounts/signup.html'

social_site_clone_project/simplesocial/groups/views.py
from django.shortcuts import render

# Create your views here.

social_site_clone_project/simplesocial/posts/views.py
from django.shortcuts import render

# Create your views here.

social_site_clone_project/simplesocial/simplesocial/views.py
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse

class TestPage(TemplateView):
    template_name = 'test.html'

class ThankPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = "index.html"

    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("test"))
        return super().get(request,*args,**kwargs)

social_site_clone_project/simplesocial/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<div class='container'>
  <h1>login </h2>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type='submit' class='btn btn-default' value="Login">
    </form>
</div>
{% endblock %}

social_site_clone_project/simplesocial/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class='container'>
  <h1>Sign Up</h2>
    <form method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type='submit' class='btn btn-default' value="Sign Up">
    </form>
</div>
{% endblock %}

social_site_clone_project/simplesocial/accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div class='container'>
  <h1>Sign Up</h2>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type='submit' class='btn btn-default' value="Sign Up">
    </form>
</div>
{% endblock %}

social_site_clone_project/simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Latest css only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

     <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

     <link rel="stylesheet" href="{% static 'simplesocial/static/css/master.css'%}">

</head>
<body>

<nav class="navbar  mynav" role="navigation" id="navbar">
     <div class="container">

       <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

         <ul class="nav navbar-nav navbar-right">
           {% if user.is_authenticated %}
                 <li><a href="#" class="btn btn-simple">Post</a></li>
                 <li><a href="#" class="btn btn-simple">Groups</a></li>
                 <li><a href="#" class="btn btn-simple">Create Group</a></li>
                 <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
           {% else %}
                 <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
                 <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
           {% endif %}
         </ul>


     </div>
   </nav>

   <div class="container mycontent">
             {% block content %}

             {% endblock %}

           </div>
</body>
</html>

social_site_clone_project/simplesocial/templates/index.html
{% extends 'base.html'%}
{% block content %}
<h1>welcome to the starsocial site</h1>
{% endblock %}

social_site_clone_project/simplesocial/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="#">Go to Groups</a></h2>


</div>




{% endblock %}

social_site_clone_project/simplesocial/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}